# Generated by Django 5.1.4 on 2026-09-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCostSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("labour_rate_minor_per_minute", models.PositiveIntegerField(default=0)),
                (
                    "press_minutes_per_garment",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("delivery_allowance_minor_per_job", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_cost_settings",
                        to="territory.hub",
                    ),
                ),
            ],
            options={
                "db_table": "territory_order_cost_settings",
            },
        ),
    ]
