# Generated by Django 5.1.4 on 2026-09-02 09:35

import common.id
import django.db.models.deletion
import django.utils.timezone
import fulfilment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordering", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PLANNED",
                        max_length=16,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_days",
                        to="territory.cluster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True, related_name="route_days", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fulfilment_route_day",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PICKUP", "Pickup"), ("DELIVERY", "Delivery")], max_length=16
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EN_ROUTE", "En route"),
                            ("ARRIVED", "Arrived"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("slot_start", models.DateTimeField(blank=True, null=True)),
                ("slot_end", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_no", models.PositiveIntegerField(default=1)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="ordering.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="fulfilment.routeday",
                    ),
                ),
            ],
            options={
                "db_table": "fulfilment_job",
            },
        ),
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("attempt_no", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("DONE", "Done"), ("FAILED", "Failed")], max_length=8
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=64)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="fulfilment.job",
                    ),
                ),
            ],
            options={
                "db_table": "fulfilment_job_attempt",
                "indexes": [
                    models.Index(fields=["job", "-at"], name="fulfilment__job_id_bfe491_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OfflineOp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("device_id", models.CharField(max_length=128)),
                ("client_op_id", models.CharField(max_length=64, unique=True)),
                ("op_type", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("client_ts", models.DateTimeField()),
                ("server_received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPLIED", "Applied"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("result_detail", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_ops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fulfilment_offline_op",
                "indexes": [
                    models.Index(
                        fields=["staff", "-server_received_at"],
                        name="fulfilment__staff_i_1ce48a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("PHOTO", "Photo"), ("OTP", "OTP"), ("SIGNATURE", "Signature")],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=fulfilment.models._proof_upload_path
                    ),
                ),
                ("otp_verified", models.BooleanField(default=False)),
                (
                    "geo_lat",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "geo_lng",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="fulfilment.job",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fulfilment_proof",
                "indexes": [
                    models.Index(fields=["job", "-at"], name="fulfilment__job_id_bb323e_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="routeday",
            index=models.Index(fields=["hub", "date"], name="fulfilment__hub_id_e7f6ea_idx"),
        ),
        migrations.AddConstraint(
            model_name="routeday",
            constraint=models.UniqueConstraint(
                fields=("cluster", "date"), name="uniq_route_day_cluster_date"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["assigned_to", "slot_start"], name="fulfilment__assigne_f021b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["hub", "status"], name="fulfilment__hub_id_dd7138_idx"),
        ),
    ]
