# Generated by Django 5.1.4 on 2026-09-03 07:02

import billing.models
import common.id
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_initial"),
        ("ordering", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "ref",
                    models.CharField(
                        default=billing.models._invoice_ref,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("subtotal_minor", models.BigIntegerField(default=0)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField(default=0)),
                ("gst_applied", models.BooleanField(default=False)),
                ("gstin_snapshot", models.CharField(blank=True, max_length=15)),
                ("price_list_version", models.PositiveIntegerField(blank=True, null=True)),
                ("snapshot", models.JSONField(blank=True, default=list)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to=billing.models._invoice_pdf_path
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="ordering.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice",
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("reason", models.CharField(max_length=255)),
                ("amount_minor", models.PositiveIntegerField()),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to=billing.models._credit_note_pdf_path
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_credit_note",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["hub", "-issued_at"], name="billing_inv_hub_id_a6e5e0_idx"),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["invoice", "-at"], name="billing_cre_invoice_d790bb_idx"),
        ),
    ]
