# Generated by Django 5.1.4 on 2026-09-03 18:22

import common.id
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI_QR", "UPI (QR at door)"),
                            ("GATEWAY", "Gateway"),
                            ("CREDIT", "Customer credit"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        default="SUCCEEDED",
                        max_length=16,
                    ),
                ),
                ("gateway_ref", models.CharField(blank=True, max_length=64)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment",
                "indexes": [
                    models.Index(fields=["invoice", "-at"], name="billing_pay_invoice_0ac5c6_idx")
                ],
            },
        ),
    ]
