# Generated by Django 5.1.4 on 2026-09-09 23:48

import common.id
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_cashdeposit_cashhandover"),
        ("ordering", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONSUMABLE", "Consumable"),
                            ("LABOUR", "Labour"),
                            ("COMMISSION", "Commission"),
                            ("DELIVERY", "Delivery"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveIntegerField()),
                ("source_ref", models.CharField(blank=True, max_length=64)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="ordering.order",
                    ),
                ),
            ],
            options={
                "db_table": "billing_order_cost",
                "indexes": [
                    models.Index(fields=["order", "-at"], name="billing_ord_order_i_5344d0_idx"),
                    models.Index(fields=["kind"], name="billing_ord_kind_214d41_idx"),
                ],
            },
        ),
    ]
