# Generated by Django 5.1.4 on 2026-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_customercredit_creditentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercost",
            name="amount_minor",
            field=models.BigIntegerField(),
        ),
    ]
