# Generated by Django 5.1.4 on 2026-10-06 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_ordercost_amount_minor"),
        ("customers", "0003_alter_customer_status"),
        ("ordering", "0003_order_idempotency_key"),
        ("territory", "0002_ordercostsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["-created_at"], name="invoice_created_idx"),
        ),
    ]
