# Generated by Django 5.1.4 on 2026-09-01 22:21

import common.id
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("customers", "0002_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("ref", models.CharField(editable=False, max_length=24, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("WHATSAPP", "WhatsApp"),
                            ("COUNTER", "Counter / walk-in"),
                            ("PHONE", "Phone"),
                            ("APP", "Mobile app"),
                        ],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_CONFIRMATION", "Pending confirmation"),
                            ("SCHEDULED", "Scheduled"),
                            ("PICKUP_ASSIGNED", "Pickup assigned"),
                            ("PICKUP_EN_ROUTE", "Pickup en route"),
                            ("PICKUP_FAILED", "Pickup failed"),
                            ("PICKED_UP", "Picked up"),
                            ("AT_HUB", "At hub"),
                            ("INTAKE_VERIFIED", "Intake verified"),
                            ("IN_PRODUCTION", "In production"),
                            ("READY", "Ready"),
                            ("DELIVERY_ASSIGNED", "Delivery assigned"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERY_FAILED", "Delivery failed"),
                            ("RETURNED_TO_HUB", "Returned to hub"),
                            ("DELIVERED", "Delivered"),
                            ("ON_HOLD", "On hold"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIALLY_PAID", "Partially paid"),
                            ("PAID", "Paid"),
                            ("WRITTEN_OFF", "Written off"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("pickup_slot_start", models.DateTimeField(blank=True, null=True)),
                ("pickup_slot_end", models.DateTimeField(blank=True, null=True)),
                ("delivery_slot_start", models.DateTimeField(blank=True, null=True)),
                ("delivery_slot_end", models.DateTimeField(blank=True, null=True)),
                ("pickup_promised_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_promised_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("declared_total_qty", models.PositiveIntegerField(default=0)),
                (
                    "verified_total_qty",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "price_list_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("estimate_minor", models.BigIntegerField(default=0)),
                ("subtotal_minor", models.BigIntegerField(default=0)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("tax_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField(default=0)),
                ("referral_code", models.CharField(blank=True, max_length=32)),
                ("offers_applied", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("cancelled_reason", models.CharField(blank=True, max_length=255)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="customers.address",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="territory.apartment",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_capacity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_orders",
                        to="territory.routedaycapacity",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "pickup_capacity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_orders",
                        to="territory.routedaycapacity",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.service",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ordering_order",
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("event_type", models.CharField(max_length=48)),
                ("from_status", models.CharField(blank=True, max_length=24)),
                ("to_status", models.CharField(blank=True, max_length=24)),
                ("actor_role", models.CharField(blank=True, max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ordering.order",
                    ),
                ),
            ],
            options={
                "db_table": "ordering_order_event",
            },
        ),
        migrations.CreateModel(
            name="OrderException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                            ("MISSING", "Missing"),
                            ("WRONG_ITEM", "Wrong item"),
                            ("REPRESS", "Re-press requested"),
                            ("COMPLAINT", "Complaint"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=8,
                    ),
                ),
                ("description", models.TextField()),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("WRITTEN_OFF", "Written off"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("cost_minor", models.BigIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="ordering.order",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ordering_order_exception",
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("declared_qty", models.PositiveIntegerField(default=0)),
                ("verified_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("unit_price_minor", models.BigIntegerField()),
                ("line_total_minor", models.BigIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "garment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.garmenttype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ordering.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ordering_order_line",
            },
        ),
        migrations.CreateModel(
            name="ReQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("reason", models.CharField(max_length=255)),
                ("old_total_minor", models.BigIntegerField()),
                ("new_total_minor", models.BigIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requotes",
                        to="ordering.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ordering_requote",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["hub", "status", "pickup_slot_start"],
                name="ordering_or_hub_id_886876_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["apartment", "-created_at"],
                name="ordering_or_apartme_30719d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="ordering_or_custome_d8d5f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "-created_at"], name="ordering_or_order_i_e665b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderexception",
            index=models.Index(
                fields=["hub", "status"], name="ordering_or_hub_id_d46ec2_idx"
            ),
        ),
    ]
