# Generated by Django 5.1.4 on 2026-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0002_order_tracking_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
