# Generated by Django 5.1.4 on 2026-10-06 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("customers", "0003_alter_customer_status"),
        ("ordering", "0003_order_idempotency_key"),
        ("territory", "0002_ordercostsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-created_at"], name="order_created_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("delivered_at__isnull", False)),
                fields=["hub", "delivered_at"],
                name="order_hub_delivered_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("delivered_at__isnull", False)),
                fields=["customer", "delivered_at"],
                name="order_cust_delivered_idx",
            ),
        ),
    ]
