# Generated by Django 5.1.4 on 2026-09-02 08:16

import common.id
import custody.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("ordering", "0001_initial"),
        ("territory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "code",
                    models.CharField(
                        default=custody.models._new_bag_code,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("garment_count", models.PositiveIntegerField(default=0)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("SORTED", "Sorted"),
                            ("PRESSING", "Pressing"),
                            ("PRESSED", "Pressed"),
                            ("QC", "Quality check"),
                            ("REWORK", "Rework"),
                            ("PACKED", "Packed"),
                            ("DISPATCHED", "Dispatched"),
                            ("DELIVERED", "Delivered"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                            ("HELD", "Held"),
                            ("RETURNED_UNPRESSED", "Returned unpressed"),
                        ],
                        default="RECEIVED",
                        max_length=24,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bags",
                        to="ordering.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custody_bag",
            },
        ),
        migrations.CreateModel(
            name="GarmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("seq", models.PositiveIntegerField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("SORTED", "Sorted"),
                            ("PRESSING", "Pressing"),
                            ("PRESSED", "Pressed"),
                            ("QC", "Quality check"),
                            ("REWORK", "Rework"),
                            ("PACKED", "Packed"),
                            ("DISPATCHED", "Dispatched"),
                            ("DELIVERED", "Delivered"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                            ("HELD", "Held"),
                            ("RETURNED_UNPRESSED", "Returned unpressed"),
                        ],
                        default="RECEIVED",
                        max_length=24,
                    ),
                ),
                ("condition_notes", models.CharField(blank=True, max_length=255)),
                ("defect_flags", models.JSONField(blank=True, default=list)),
                ("is_rework", models.BooleanField(default=False)),
                ("rework_count", models.PositiveIntegerField(default=0)),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_lines",
                        to="custody.bag",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "garment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.garmenttype",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_lines",
                        to="ordering.orderline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custody_garment_line",
            },
        ),
        migrations.CreateModel(
            name="QcCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "result",
                    models.CharField(choices=[("PASS", "Pass"), ("FAIL", "Fail")], max_length=8),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "garment_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_checks",
                        to="custody.garmentline",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custody_qc_check",
            },
        ),
        migrations.CreateModel(
            name="StageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("from_stage", models.CharField(blank=True, max_length=24)),
                ("to_stage", models.CharField(max_length=24)),
                ("station", models.CharField(blank=True, max_length=64)),
                ("scanned", models.BooleanField(default=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("device_id", models.CharField(blank=True, max_length=128)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_events",
                        to="custody.bag",
                    ),
                ),
                (
                    "garment_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_events",
                        to="custody.garmentline",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
            ],
            options={
                "db_table": "custody_stage_event",
            },
        ),
        migrations.AddIndex(
            model_name="bag",
            index=models.Index(
                fields=["hub", "current_stage"], name="custody_bag_hub_id_ab7492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="garmentline",
            index=models.Index(fields=["stage", "hub"], name="custody_gar_stage_7c616f_idx"),
        ),
        migrations.AddConstraint(
            model_name="garmentline",
            constraint=models.UniqueConstraint(
                fields=("bag", "seq"), name="uniq_custody_garmentline_bag_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="qccheck",
            index=models.Index(
                fields=["garment_line", "-at"], name="custody_qc__garment_800c69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stageevent",
            index=models.Index(
                fields=["bag", "-occurred_at"], name="custody_sta_bag_id_57dde9_idx"
            ),
        ),
    ]
