# Generated by Django 5.1.4 on 2026-10-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefSequence",
            fields=[
                ("key", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "common_ref_sequence",
            },
        ),
    ]
