# Generated by Django 5.1.4 on 2026-09-01 22:21

import common.id
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GarmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                ("default_press_seconds", models.PositiveIntegerField(default=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_garment_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FIRST_ORDER", "First order discount"),
                            ("REFERRAL_CREDIT", "Referral credit"),
                            ("APARTMENT_PROMO", "Apartment promotion"),
                            ("FLAT", "Flat discount"),
                            ("PERCENT", "Percent discount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_bps",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Basis points for PERCENT; ignored otherwise",
                    ),
                ),
                (
                    "value_minor",
                    models.BigIntegerField(
                        default=0, help_text="Minor units for FLAT/credit offers"
                    ),
                ),
                ("cap_minor", models.BigIntegerField(blank=True, null=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redemptions_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_offer",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "cycle",
                    models.CharField(
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                        max_length=16,
                    ),
                ),
                ("included_qty", models.PositiveIntegerField()),
                ("price_minor", models.BigIntegerField()),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_package",
            },
        ),
        migrations.CreateModel(
            name="PriceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("unit_price_minor", models.BigIntegerField()),
                ("min_qty", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "catalog_price_line",
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "catalog_price_list",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PER_ITEM", "Per item"),
                            ("PER_KG", "Per kilogram"),
                            ("PER_PAIR", "Per pair"),
                        ],
                        default="PER_ITEM",
                        max_length=16,
                    ),
                ),
                ("sla_hours", models.PositiveIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "catalog_service",
                "ordering": ["name"],
            },
        ),
    ]
