# Generated by Django 5.1.4 on 2026-09-01 22:21

import common.id
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("flat_no", models.CharField(blank=True, max_length=32)),
                ("block", models.CharField(blank=True, max_length=32)),
                ("landmark", models.CharField(blank=True, max_length=160)),
                ("free_text_address", models.TextField(blank=True)),
                ("label", models.CharField(default="Home", max_length=32)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "customers_address",
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service communication"),
                            ("MARKETING", "Marketing"),
                            ("WHATSAPP", "WhatsApp messaging"),
                        ],
                        max_length=16,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "customers_consent_record",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("preferred_language", models.CharField(default="en", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("ACTIVE", "Active"),
                            ("LAPSED", "Lapsed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="LEAD",
                        max_length=16,
                    ),
                ),
                ("first_order_at", models.DateTimeField(blank=True, null=True)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
                ("lifetime_orders", models.PositiveIntegerField(default=0)),
                ("lifetime_gross_minor", models.BigIntegerField(default=0)),
                ("acquisition_channel", models.CharField(blank=True, max_length=32)),
                ("acquisition_partner_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "customers_customer",
            },
        ),
        migrations.CreateModel(
            name="CustomerMergeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("merged_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "customers_merge_log",
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("body", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "customers_note",
            },
        ),
    ]
