# Generated by Django 5.1.4 on 2026-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("LEAD", "Lead"),
                    ("ACTIVE", "Active"),
                    ("LAPSED", "Lapsed"),
                    ("BLOCKED", "Blocked"),
                    ("DELETED", "Deleted"),
                ],
                default="LEAD",
                max_length=16,
            ),
        ),
    ]
