# Generated by Django 5.1.4 on 2026-10-02 19:21

import common.id
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        ("growth", "0003_seed_channels"),
        ("ordering", "0003_order_idempotency_key"),
        ("territory", "0002_ordercostsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("is_first_touch", models.BooleanField(default=False)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("CODE", "Referral code"),
                            ("SELF_REPORTED", "Customer said so"),
                            ("ORDER_CHANNEL", "How the order came in"),
                            ("DEFAULT", "Fallback (unknown)"),
                            ("BACKFILL", "Backfilled from older data"),
                        ],
                        max_length=16,
                    ),
                ),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="territory.apartment",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="growth.channel",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributions",
                        to="customers.customer",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ordering.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="growth.referralpartner",
                    ),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="growth.referralcode",
                    ),
                ),
            ],
            options={
                "db_table": "growth_attribution",
                "indexes": [
                    models.Index(
                        fields=["channel", "captured_at"], name="growth_attr_channel_89cdf7_idx"
                    ),
                    models.Index(
                        fields=["apartment", "captured_at"], name="growth_attr_apartme_bf0280_idx"
                    ),
                    models.Index(
                        fields=["customer", "captured_at"], name="growth_attr_custome_bed348_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_first_touch", True)),
                        fields=("customer",),
                        name="uniq_growth_attribution_first_touch_per_customer",
                    )
                ],
            },
        ),
    ]
