# Generated by Django 5.1.4 on 2026-10-03 17:10

import common.id
import django.db.models.deletion
import django.utils.timezone
import growth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0005_backfill_attribution"),
        ("ordering", "0003_order_idempotency_key"),
        ("territory", "0002_ordercostsettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("PER_ORDER", "Fixed amount per order"),
                            ("PER_ITEM", "Fixed amount per item"),
                            ("PERCENT_OF_ORDER", "Percent of order value"),
                            ("FLAT_FIRST_ORDER", "Flat amount, first order only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("FIRST_ORDER_ONLY", "Customer's first order only"),
                            ("ALL_ORDERS", "Every order"),
                            ("FIRST_N_ORDERS", "Customer's first N orders"),
                        ],
                        default="FIRST_ORDER_ONLY",
                        max_length=20,
                    ),
                ),
                ("first_n", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cap_minor", models.PositiveIntegerField(blank=True, null=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_commission_rule",
            },
        ),
        migrations.AddField(
            model_name="referralpartner",
            name="commission_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partners",
                to="growth.commissionrule",
            ),
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "ref",
                    models.CharField(
                        default=growth.models._settlement_ref,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField()),
                ("total_minor", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting payment"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=16)),
                ("payment_ref", models.CharField(blank=True, max_length=64)),
                (
                    "statement_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to=growth.models._statement_pdf_path
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="growth.referralpartner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_settlement",
            },
        ),
        migrations.CreateModel(
            name="CommissionAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.id.new_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("rule_terms", models.JSONField(default=dict)),
                ("amount_minor", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCRUED", "Accrued"),
                            ("APPROVED", "In a settlement"),
                            ("SETTLED", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="ACCRUED",
                        max_length=16,
                    ),
                ),
                ("accrued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="territory.hub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ordering.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accruals",
                        to="growth.referralpartner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accruals",
                        to="growth.commissionrule",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accruals",
                        to="growth.settlement",
                    ),
                ),
            ],
            options={
                "db_table": "growth_commission_accrual",
            },
        ),
        migrations.AddIndex(
            model_name="commissionrule",
            index=models.Index(fields=["hub", "is_default"], name="growth_comm_hub_id_5b1d7e_idx"),
        ),
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(fields=["partner", "status"], name="growth_sett_partner_11eb99_idx"),
        ),
        migrations.AddIndex(
            model_name="commissionaccrual",
            index=models.Index(fields=["partner", "status"], name="growth_comm_partner_8ba624_idx"),
        ),
        migrations.AddConstraint(
            model_name="commissionaccrual",
            constraint=models.UniqueConstraint(
                fields=("partner", "order"), name="growth_accrual_once_per_partner_order"
            ),
        ),
    ]
