"""Weekly pack exports (docs/07 §4.3, docs/08 batch 6.8): Excel with one
sheet per metric's drill-down plus a summary and a parameters sheet, and
CSV for a single metric. Money arrives as numbers formatted as rupees, not
strings, so the file can be pivoted without cleaning."""

from __future__ import annotations

import csv
import io
from datetime import date, timedelta

from django.utils import timezone
from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from analytics import metrics

RUPEES = '"₹"#,##0.00'


def _is_money(key: str) -> bool:
    return key.endswith("_minor") or key in metrics.COST_KINDS


def _cell(key: str, value):
    if _is_money(key) and isinstance(value, int):
        return value / 100
    return value


def _header(key: str) -> str:
    return key.removesuffix("_minor").replace("_", " ").capitalize()


def _write_rows(ws, rows: list[dict]) -> None:
    if not rows:
        ws.append(["No rows for this week."])
        return
    keys = list(rows[0].keys())
    ws.append([_header(k) for k in keys])
    for cell in ws[1]:
        cell.font = Font(bold=True)
    ws.freeze_panes = "A2"
    for row in rows:
        ws.append([_cell(k, row.get(k)) for k in keys])
    for idx, key in enumerate(keys, start=1):
        letter = get_column_letter(idx)
        if _is_money(key):
            for (cell,) in ws.iter_rows(min_row=2, min_col=idx, max_col=idx):
                cell.number_format = RUPEES
        ws.column_dimensions[letter].width = max(12, min(40, len(_header(key)) + 6))


def weekly_workbook(hub, week_start: date, *, include_money: bool, generated_by: str) -> bytes:
    wb = Workbook()
    summary = wb.active
    summary.title = "Summary"
    summary.append(["Metric", "This week", "Last week"])
    for cell in summary[1]:
        cell.font = Font(bold=True)
    pack = metrics.weekly(hub, week_start, include_money=include_money)
    for tile in pack["tiles"]:
        if tile["restricted"]:
            summary.append([tile["label"], "Founder only", ""])
            continue
        money = tile["key"] in ("acquisition_cost", "average_order_value", "contribution")
        value, previous = tile["value"], tile["previous"]
        summary.append(
            [
                tile["label"],
                value / 100 if money and isinstance(value, int) else value,
                previous / 100 if money and isinstance(previous, int) else previous,
            ]
        )
        if money:
            for cell in summary[summary.max_row][1:]:
                cell.number_format = RUPEES
    summary.column_dimensions["A"].width = 30
    summary.column_dimensions["B"].width = 16
    summary.column_dimensions["C"].width = 16

    for key, (label, _fn, founder_only) in metrics.METRICS.items():
        if founder_only and not include_money:
            continue
        ws = wb.create_sheet(title=label[:31])
        _write_rows(ws, metrics.metric_rows(hub, key, week_start)["rows"])

    params = wb.create_sheet(title="Parameters")
    for row in (
        ("Hub", hub.name),
        ("Week", f"{week_start} to {week_start + timedelta(days=6)} (Mon–Sun, IST)"),
        ("Generated", timezone.localtime().strftime("%d %b %Y %H:%M IST")),
        ("Generated by", generated_by),
        ("Note", "Money in rupees. New customers count on their first delivered order."),
    ):
        params.append(row)
    params.column_dimensions["A"].width = 16
    params.column_dimensions["B"].width = 60

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()


def metric_csv(hub, key: str, week_start: date) -> str:
    rows = metrics.metric_rows(hub, key, week_start)["rows"]
    out = io.StringIO()
    if rows:
        writer = csv.DictWriter(out, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow({k: _cell(k, v) for k, v in row.items()})
    return out.getvalue()


_MONEY_TILES = ("acquisition_cost", "average_order_value", "contribution")


def _display(key, value) -> str:
    if value is None:
        return "—"
    if key in _MONEY_TILES:
        return f"₹{value / 100:,.2f}"
    if key == "on_time":
        return f"{value}%"
    if key == "feedback":
        return f"{value:.1f} / 5"
    return str(value)


def _detail(tile: dict) -> str:
    k = tile["key"]
    if k == "repeat_customers":
        return f"Cohort repeat: {tile['cohort_repeated']}/{tile['cohort_size']}" + (
            " (maturing)" if tile.get("cohort_maturing") else ""
        )
    if k == "orders_per_customer":
        return f"{tile['orders']} orders · {tile['active_customers']} customers"
    if k == "acquisition_cost":
        return f"Paid channels {_display(k, tile.get('paid_cac_minor'))}"
    if k == "referrals":
        return f"Watchmen {tile['watchman']} · customers {tile['customer_referral']}"
    if k == "apartments":
        return f"Busiest: {tile['top']}" if tile.get("top") else ""
    if k == "average_order_value":
        return f"Median {_display(k, tile.get('median_minor'))} · {tile['orders']} orders"
    if k == "contribution":
        return f"{tile.get('margin_pct')}% margin, before fixed costs"
    if k == "on_time":
        return f"{tile.get('excluding_customer_caused')}% excluding customer no-shows"
    if k == "feedback":
        return f"{tile['responses']} ratings · {tile.get('response_rate')}% responded"
    return ""


def weekly_pdf(hub, week_start: date, *, include_money: bool, generated_by: str) -> bytes:
    from django.template.loader import render_to_string
    from weasyprint import HTML

    pack = metrics.weekly(hub, week_start, include_money=include_money)
    tiles = []
    for tile in pack["tiles"]:
        if tile["restricted"]:
            tiles.append(tile)
            continue
        value, previous = tile["value"], tile["previous"]
        if value is None or previous is None:
            delta = "No comparison with last week"
        elif value == previous:
            delta = "Same as last week"
        else:
            delta = f"{'Up' if value > previous else 'Down'} from {_display(tile['key'], previous)}"
        tiles.append(
            {
                **tile,
                "display": _display(tile["key"], value),
                "delta": delta,
                "detail": _detail(tile),
            }
        )
    html = render_to_string(
        "analytics/weekly.html",
        {
            "hub": hub,
            "week_label": f"{week_start:%d %b} – {week_start + timedelta(days=6):%d %b %Y}",
            "tile_pairs": [tiles[i : i + 2] for i in range(0, len(tiles), 2)],
            "generated": timezone.localtime().strftime("%d %b %Y, %H:%M IST"),
            "generated_by": generated_by,
        },
    )
    return HTML(string=html).write_pdf()
