# Generated by Django 5.1.4 on 2026-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_initial"),
        ("territory", "0002_ordercostsettings"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["-created_at"], name="audit_created_idx"),
        ),
    ]
